sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
sqlite3 database.sdb < main.sql
